version: '3.2'

services:
    api:
        build: api
        container_name: piston_api
        privileged: true
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        environment:
            - PISTON_MAX_CONCURRENT_JOBS=60
            - PISTON_OUTPUT_MAX_SIZE=2048
            - PISTON_MAX_OPEN_FILES=20
            - PISTON_COMPILE_TIMEOUT=20000
            - PISTON_RUN_TIMEOUT=120000
            - PISTON_RUN_CPU_TIME=120000
            - PISTON_RUN_MEMORY_LIMIT=256000000
            - PISTON_REPO_URL=http://repo:8000/index
            - PISTON_API_NONCE_ENCRYPTION_KEY=placeholder
            - PISTON_API_NONCE_ENCRYPTION_IV=placeholder

    repo: # Local testing of packages
        build: repo
        container_name: piston_repo
        command: ['--no-build'] # Don't build anything
        volumes:
            - .:/piston
